version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/android:2023.07
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      # これがないとprivate.propertiesが無くてエラーが出る
      - run:
          name: Create private.properties
          command: |
            cat <<EOF > private.properties
            RELEASE_AD_BANNER_UNIT_ID=""
            DEBUG_AD_BANNER_UNIT_ID=""
            EOF
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Install Bundler
          command: sudo gem install bundler:2.4.12
      - run:
          name: ktlint Check
          command: ./gradlew --continue ktlintCheck
      - run:
          name: Test
          command: ./gradlew testDebug --stacktrace
      - run:
          name: Unit Test
          command: ./gradlew testDebugUnitTest

workflows:
  version: 2
  test:
    jobs:
      - build-and-test

