version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/android:2023.07
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}

      - run:
          command: sudo gem install bundler:2.4.12
      - run:
          name: ktlint Check
          command: ./gradlew --continue ktlintCheck

      - run:
          name: Run Danger
          command: |
            gem install Danger
            danger

workflows:
  test:
    jobs:
      - build-and-test

